In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_predict, cross_val_score

In [4]:
data = pd.read_csv("G:\HIGGS.csv", nrows=50000, header=None)

In [5]:
test = pd.read_csv("G:\HIGGS.csv", nrows=50000, skiprows=10500000, header=None)

In [6]:
rf_model = RandomForestClassifier()
lr_model = LogisticRegression()

In [11]:
target = data[0]
x = data.loc[:,1:]

In [12]:
x

1         2         3         4         5         6         7   \
0      0.869293 -0.635082  0.225690  0.327470 -0.689993  0.754202 -0.248573   
1      0.907542  0.329147  0.359412  1.497970 -0.313010  1.095531 -0.557525   
2      0.798835  1.470639 -1.635975  0.453773  0.425629  1.104875  1.282322   
3      1.344385 -0.876626  0.935913  1.992050  0.882454  1.786066 -1.646778   
4      1.105009  0.321356  1.522401  0.882808 -1.205349  0.681466 -1.070464   
...         ...       ...       ...       ...       ...       ...       ...   
49995  0.620218 -0.823058  0.157442  1.442791  0.767518  2.327923  0.344575   
49996  0.686833 -1.711317 -1.417914  1.311205 -0.298519  0.517214 -1.012040   
49997  0.728559 -1.834037 -1.397939  0.344134 -0.390320  0.951158 -0.165394   
49998  1.477981 -0.818188 -1.546087  0.835522 -1.267488  0.785623  0.013838   
49999  1.769149  1.725819 -1.643743  0.601503  1.701371  0.670656  1.387287   

             8         9         10  ...        19        20        21  \
0     -1.092064  0.000000  1.374992  ... -0.010455 -0.045767  3.101961   
1     -1.588230  2.173076  0.812581  ... -1.138930 -0.000819  0.000000   
2      1.381664  0.000000  0.851737  ...  1.128848  0.900461  0.000000   
3     -0.942383  0.000000  2.423265  ... -0.678379 -1.360356  0.000000   
4     -0.921871  0.000000  0.800872  ... -0.373566  0.113041  0.000000   
...         ...       ...       ...  ...       ...       ...       ...   
49995 -0.072010  0.000000  1.762271  ... -2.329035  1.499211  0.000000   
49996 -1.190188  0.000000  0.570343  ... -1.039824  0.303930  3.101961   
49997 -1.400851  0.000000  1.260420  ...  2.004978  0.829432  0.000000   
49998  0.079991  2.173076  0.677361  ... -0.616750  0.572508  0.000000   
49999 -0.580930  0.000000  0.773929  ...  1.596894  0.028139  0.000000   

             22        23        24        25        26        27        28  
0      1.353760  0.979563  0.978076  0.920005  0.721657  0.988751  0.876678  
1      0.302220  0.833048  0.985700  0.978098  0.779732  0.992356  0.798343  
2      0.909753  1.108330  0.985692  0.951331  0.803252  0.865924  0.780118  
3      0.946652  1.028704  0.998656  0.728281  0.869200  1.026736  0.957904  
4      0.755856  1.361057  0.986610  0.838085  1.133295  0.872245  0.808487  
...         ...       ...       ...       ...       ...       ...       ...  
49995  1.733151  1.019404  0.991311  1.722911  0.900219  1.075457  1.077989  
49996  0.715210  0.735663  1.112954  0.706047  0.276972  0.600938  0.591874  
49997  0.636411  0.983770  0.996603  0.929728  0.862690  0.934698  0.954439  
49998  0.526324  0.893976  0.977501  0.814417  0.756959  0.958430  0.842852  
49999  0.568262  0.964058  0.988136  0.956721  0.381829  0.826234  0.786691  

[50000 rows x 28 columns]

In [18]:
rf_preds = cross_val_predict(rf_model, x, target, cv=5, method='predict_proba')

In [19]:
lr_pred = cross_val_predict(lr_model, x, target, cv=5, method='predict_proba')

In [20]:
print(cross_val_score(rf_model, x, target, cv=5))
print(cross_val_score(lr_model, x, target, cv=5))

[0.7144 0.7073 0.7109 0.7135 0.7102]
[0.6456 0.6451 0.6399 0.6352 0.6353]


In [22]:
rf_preds[:,1]

array([0.51, 0.72, 0.94, ..., 0.49, 0.75, 0.47])

In [24]:
lr_pred[:,1]

array([0.62644952, 0.61947771, 0.6757202 , ..., 0.53194518, 0.50572977,
       0.59886085])

In [34]:
new = pd.DataFrame(rf_preds[:,1])

In [36]:
new['lr']=lr_pred[:,1]

In [37]:
new

0        lr
0      0.51  0.626450
1      0.72  0.619478
2      0.94  0.675720
3      0.68  0.600039
4      0.54  0.485716
...     ...       ...
49995  0.69  0.806925
49996  0.22  0.626240
49997  0.49  0.531945
49998  0.75  0.505730
49999  0.47  0.598861

[50000 rows x 2 columns]

In [40]:
from sklearn.linear_model import LinearRegression
final = LinearRegression()
final_predict = cross_val_predict(final, new, target, cv=5)

In [41]:
final_predict

array([0.52342388, 0.769961  , 1.03768711, ..., 0.48119613, 0.78460663,
       0.46819987])

In [42]:
guess = pd.DataFrame(final_predict)

In [44]:
guess['predict']=0

In [50]:
guess.loc[guess[0]>0.5,"predict"]=1

In [52]:
from sklearn.metrics import accuracy_score
accuracy_score(guess['predict'],target)

0.713

In [53]:
data

0         1         2         3         4         5         6   \
0      1.0  0.869293 -0.635082  0.225690  0.327470 -0.689993  0.754202   
1      1.0  0.907542  0.329147  0.359412  1.497970 -0.313010  1.095531   
2      1.0  0.798835  1.470639 -1.635975  0.453773  0.425629  1.104875   
3      0.0  1.344385 -0.876626  0.935913  1.992050  0.882454  1.786066   
4      1.0  1.105009  0.321356  1.522401  0.882808 -1.205349  0.681466   
...    ...       ...       ...       ...       ...       ...       ...   
49995  1.0  0.620218 -0.823058  0.157442  1.442791  0.767518  2.327923   
49996  0.0  0.686833 -1.711317 -1.417914  1.311205 -0.298519  0.517214   
49997  0.0  0.728559 -1.834037 -1.397939  0.344134 -0.390320  0.951158   
49998  1.0  1.477981 -0.818188 -1.546087  0.835522 -1.267488  0.785623   
49999  0.0  1.769149  1.725819 -1.643743  0.601503  1.701371  0.670656   

             7         8         9   ...        19        20        21  \
0     -0.248573 -1.092064  0.000000  ... -0.010455 -0.045767  3.101961   
1     -0.557525 -1.588230  2.173076  ... -1.138930 -0.000819  0.000000   
2      1.282322  1.381664  0.000000  ...  1.128848  0.900461  0.000000   
3     -1.646778 -0.942383  0.000000  ... -0.678379 -1.360356  0.000000   
4     -1.070464 -0.921871  0.000000  ... -0.373566  0.113041  0.000000   
...         ...       ...       ...  ...       ...       ...       ...   
49995  0.344575 -0.072010  0.000000  ... -2.329035  1.499211  0.000000   
49996 -1.012040 -1.190188  0.000000  ... -1.039824  0.303930  3.101961   
49997 -0.165394 -1.400851  0.000000  ...  2.004978  0.829432  0.000000   
49998  0.013838  0.079991  2.173076  ... -0.616750  0.572508  0.000000   
49999  1.387287 -0.580930  0.000000  ...  1.596894  0.028139  0.000000   

             22        23        24        25        26        27        28  
0      1.353760  0.979563  0.978076  0.920005  0.721657  0.988751  0.876678  
1      0.302220  0.833048  0.985700  0.978098  0.779732  0.992356  0.798343  
2      0.909753  1.108330  0.985692  0.951331  0.803252  0.865924  0.780118  
3      0.946652  1.028704  0.998656  0.728281  0.869200  1.026736  0.957904  
4      0.755856  1.361057  0.986610  0.838085  1.133295  0.872245  0.808487  
...         ...       ...       ...       ...       ...       ...       ...  
49995  1.733151  1.019404  0.991311  1.722911  0.900219  1.075457  1.077989  
49996  0.715210  0.735663  1.112954  0.706047  0.276972  0.600938  0.591874  
49997  0.636411  0.983770  0.996603  0.929728  0.862690  0.934698  0.954439  
49998  0.526324  0.893976  0.977501  0.814417  0.756959  0.958430  0.842852  
49999  0.568262  0.964058  0.988136  0.956721  0.381829  0.826234  0.786691  

[50000 rows x 29 columns]

In [54]:
y = data[0]

In [58]:
blended = data.iloc[:,-4:]

In [59]:
blended

25        26        27        28
0      0.920005  0.721657  0.988751  0.876678
1      0.978098  0.779732  0.992356  0.798343
2      0.951331  0.803252  0.865924  0.780118
3      0.728281  0.869200  1.026736  0.957904
4      0.838085  1.133295  0.872245  0.808487
...         ...       ...       ...       ...
49995  1.722911  0.900219  1.075457  1.077989
49996  0.706047  0.276972  0.600938  0.591874
49997  0.929728  0.862690  0.934698  0.954439
49998  0.814417  0.756959  0.958430  0.842852
49999  0.956721  0.381829  0.826234  0.786691

[50000 rows x 4 columns]

In [62]:
fl_data = data.iloc[:,1:25]

In [63]:
rf_preds = cross_val_predict(rf_model, fl_data, target, cv=5, method='predict_proba')

In [66]:
lr_preds = cross_val_predict(lr_model, fl_data, target, cv=5, method='predict_proba')

In [68]:
fl_data['lr_preds']=lr_preds[:,1]

<ipython-input-68-effcbea3ee79>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl_data['lr_preds']=lr_preds[:,1]


In [70]:
fl_data['rf_preds']=rf_preds[:,1]

<ipython-input-70-82d5c0684a8c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl_data['rf_preds']=rf_preds[:,1]


In [71]:
fl_data

1         2         3         4         5         6         7  \
0      0.869293 -0.635082  0.225690  0.327470 -0.689993  0.754202 -0.248573   
1      0.907542  0.329147  0.359412  1.497970 -0.313010  1.095531 -0.557525   
2      0.798835  1.470639 -1.635975  0.453773  0.425629  1.104875  1.282322   
3      1.344385 -0.876626  0.935913  1.992050  0.882454  1.786066 -1.646778   
4      1.105009  0.321356  1.522401  0.882808 -1.205349  0.681466 -1.070464   
...         ...       ...       ...       ...       ...       ...       ...   
49995  0.620218 -0.823058  0.157442  1.442791  0.767518  2.327923  0.344575   
49996  0.686833 -1.711317 -1.417914  1.311205 -0.298519  0.517214 -1.012040   
49997  0.728559 -1.834037 -1.397939  0.344134 -0.390320  0.951158 -0.165394   
49998  1.477981 -0.818188 -1.546087  0.835522 -1.267488  0.785623  0.013838   
49999  1.769149  1.725819 -1.643743  0.601503  1.701371  0.670656  1.387287   

              8         9        10  ...        17        18        19  \
0     -1.092064  0.000000  1.374992  ...  0.000000  0.657930 -0.010455   
1     -1.588230  2.173076  0.812581  ...  0.000000  0.398701 -1.138930   
2      1.381664  0.000000  0.851737  ...  2.548224  1.256955  1.128848   
3     -0.942383  0.000000  2.423265  ...  0.000000  0.745313 -0.678379   
4     -0.921871  0.000000  0.800872  ...  0.000000  0.479999 -0.373566   
...         ...       ...       ...  ...       ...       ...       ...   
49995 -0.072010  0.000000  1.762271  ...  0.000000  1.535169 -2.329035   
49996 -1.190188  0.000000  0.570343  ...  0.000000  1.006489 -1.039824   
49997 -1.400851  0.000000  1.260420  ...  2.548224  0.595617  2.004978   
49998  0.079991  2.173076  0.677361  ...  2.548224  0.460526 -0.616750   
49999 -0.580930  0.000000  0.773929  ...  1.274112  0.606327  1.596894   

             20        21        22        23        24  lr_preds  rf_preds  
0     -0.045767  3.101961  1.353760  0.979563  0.978076  0.590598      0.58  
1     -0.000819  0.000000  0.302220  0.833048  0.985700  0.444271      0.60  
2      0.900461  0.000000  0.909753  1.108330  0.985692  0.559473      0.71  
3     -1.360356  0.000000  0.946652  1.028704  0.998656  0.431329      0.57  
4      0.113041  0.000000  0.755856  1.361057  0.986610  0.554937      0.59  
...         ...       ...       ...       ...       ...       ...       ...  
49995  1.499211  0.000000  1.733151  1.019404  0.991311  0.641463      0.71  
49996  0.303930  3.101961  0.715210  0.735663  1.112954  0.543205      0.33  
49997  0.829432  0.000000  0.636411  0.983770  0.996603  0.574727      0.44  
49998  0.572508  0.000000  0.526324  0.893976  0.977501  0.447516      0.54  
49999  0.028139  0.000000  0.568262  0.964058  0.988136  0.485016      0.40  

[50000 rows x 26 columns]

In [73]:
rf_final = RandomForestClassifier()
rf_final.fit(fl_data, target)

RandomForestClassifier()

In [74]:
data

0         1         2         3         4         5         6   \
0      1.0  0.869293 -0.635082  0.225690  0.327470 -0.689993  0.754202   
1      1.0  0.907542  0.329147  0.359412  1.497970 -0.313010  1.095531   
2      1.0  0.798835  1.470639 -1.635975  0.453773  0.425629  1.104875   
3      0.0  1.344385 -0.876626  0.935913  1.992050  0.882454  1.786066   
4      1.0  1.105009  0.321356  1.522401  0.882808 -1.205349  0.681466   
...    ...       ...       ...       ...       ...       ...       ...   
49995  1.0  0.620218 -0.823058  0.157442  1.442791  0.767518  2.327923   
49996  0.0  0.686833 -1.711317 -1.417914  1.311205 -0.298519  0.517214   
49997  0.0  0.728559 -1.834037 -1.397939  0.344134 -0.390320  0.951158   
49998  1.0  1.477981 -0.818188 -1.546087  0.835522 -1.267488  0.785623   
49999  0.0  1.769149  1.725819 -1.643743  0.601503  1.701371  0.670656   

             7         8         9   ...        19        20        21  \
0     -0.248573 -1.092064  0.000000  ... -0.010455 -0.045767  3.101961   
1     -0.557525 -1.588230  2.173076  ... -1.138930 -0.000819  0.000000   
2      1.282322  1.381664  0.000000  ...  1.128848  0.900461  0.000000   
3     -1.646778 -0.942383  0.000000  ... -0.678379 -1.360356  0.000000   
4     -1.070464 -0.921871  0.000000  ... -0.373566  0.113041  0.000000   
...         ...       ...       ...  ...       ...       ...       ...   
49995  0.344575 -0.072010  0.000000  ... -2.329035  1.499211  0.000000   
49996 -1.012040 -1.190188  0.000000  ... -1.039824  0.303930  3.101961   
49997 -0.165394 -1.400851  0.000000  ...  2.004978  0.829432  0.000000   
49998  0.013838  0.079991  2.173076  ... -0.616750  0.572508  0.000000   
49999  1.387287 -0.580930  0.000000  ...  1.596894  0.028139  0.000000   

             22        23        24        25        26        27        28  
0      1.353760  0.979563  0.978076  0.920005  0.721657  0.988751  0.876678  
1      0.302220  0.833048  0.985700  0.978098  0.779732  0.992356  0.798343  
2      0.909753  1.108330  0.985692  0.951331  0.803252  0.865924  0.780118  
3      0.946652  1.028704  0.998656  0.728281  0.869200  1.026736  0.957904  
4      0.755856  1.361057  0.986610  0.838085  1.133295  0.872245  0.808487  
...         ...       ...       ...       ...       ...       ...       ...  
49995  1.733151  1.019404  0.991311  1.722911  0.900219  1.075457  1.077989  
49996  0.715210  0.735663  1.112954  0.706047  0.276972  0.600938  0.591874  
49997  0.636411  0.983770  0.996603  0.929728  0.862690  0.934698  0.954439  
49998  0.526324  0.893976  0.977501  0.814417  0.756959  0.958430  0.842852  
49999  0.568262  0.964058  0.988136  0.956721  0.381829  0.826234  0.786691  

[50000 rows x 29 columns]

In [77]:
x_train = data.loc[:,1:]
y_train = data.loc[:,0]

In [78]:
rf_preds = cross_val_predict(rf_model, x_train, y_train, cv=5, method='predict_proba')

In [79]:
lr_preds = cross_val_predict(lr_model, x_train, y_train, cv=5, method='predict_proba')

In [83]:
rf_model2 = RandomForestClassifier()
rf_model2.fit(x_train, y_train)
lr_model2 = LogisticRegression()
lr_model2.fit(x_train,y_train)

LogisticRegression()

In [84]:
level2_data = pd.DataFrame(rf_preds[:,1])
level2_data['lr'] = lr_preds[:,1]

In [91]:
linear_final_oof = LinearRegression()
linear_final_oof.fit(level2_data, y_train)

LinearRegression()

In [87]:
rf_infold = rf_model2.predict_proba(x_train)
lr_infold = lr_model2.predict_proba(x_train)

In [88]:
level2_infold = pd.DataFrame(rf_infold[:,1])
level2_infold['lr'] = lr_infold[:,1]

In [90]:
linear_final_if = LinearRegression()
linear_final_if.fit(level2_infold, y_train)

LinearRegression()

In [95]:
x_test = test.loc[:,1:]
y_test = test.loc[:,0]

In [97]:
test_rf = rf_model2.predict_proba(x_test)
test_lr = lr_model2.predict_proba(x_test)

In [98]:
test_final = pd.DataFrame(test_rf[:,1])
test_final['lr'] = test_lr[:,1]

In [106]:
oof_preds = linear_final_oof.predict(test_final)

In [103]:
if_preds = linear_final_if.predict(test_final)

In [104]:
from sklearn.metrics import roc_auc_score

In [108]:
roc_auc_score(y_test, oof_preds)

0.7965671797801486

In [109]:
roc_auc_score(y_test, if_preds)

0.7906164855798068

### Level 1

In [113]:
rf_level1 = RandomForestClassifier()
lr_level1 = LogisticRegression()
rf1 = cross_val_predict(rf_level1, x_train, y_train, cv =3, method='predict_proba')
lr1 = cross_val_predict(lr_level1, x_train, y_train, cv =4, method='predict_proba')

In [111]:
rf_level2 = RandomForestClassifier()
lr_level2 = LogisticRegression()

In [114]:
level2_data = pd.DataFrame(rf1[:,1])
level2_data['lr'] = lr1[:,1]

In [116]:
rf2 = cross_val_predict(rf_level2, level2_data, y_train, cv =3, method='predict_proba')
lr2 = cross_val_predict(lr_level2, level2_data, y_train, cv =3, method='predict_proba')

In [117]:
final_model = LinearRegression()


In [118]:
level3_data = pd.DataFrame(rf2[:,1])
level3_data['lr'] = lr2[:,1]

In [120]:
final_model.fit(level3_data, y_train)

LinearRegression()