In [1]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC

In [3]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target

In [4]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
my_model = SVC(C=1, kernel='linear')

In [7]:
my_model.fit(X,y)

SVC(C=1, kernel='linear')

In [8]:
my_model.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
from sklearn.metrics import accuracy_score
accuracy_score(my_model.predict(X), y)

0.9933333333333333

In [11]:
from sklearn.model_selection import cross_val_score
cross_val_score(my_model, X, y, cv=5, scoring='accuracy')

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [12]:
for i in [1E-3,1E-2,1E-1,1, 10, 100, 1000]:
    my_model.C = i
    print(i, cross_val_score(my_model, X, y, cv=5, scoring='accuracy'))

0.001 [0.86666667 0.96666667 0.83333333 0.96666667 0.93333333]
0.01 [0.9        0.96666667 0.86666667 0.96666667 0.9       ]
0.1 [0.96666667 0.96666667 0.96666667 0.96666667 1.        ]
1 [0.96666667 1.         0.96666667 0.96666667 1.        ]
10 [1.         1.         0.9        0.96666667 1.        ]
100 [1.         1.         0.9        0.93333333 1.        ]
1000 [1.         1.         0.9        0.93333333 1.        ]


In [13]:
from sklearn.datasets import load_digits
data = load_digits()

In [15]:
X = data['data']
y = data['target']

In [17]:
for i in [1E-4,1E-3,1E-2,1E-1]:
    my_model.C = i
    print(i, cross_val_score(my_model, X, y, cv=5, scoring='accuracy'))

0.0001 [0.92222222 0.90833333 0.95821727 0.97214485 0.89415042]
0.001 [0.95       0.91944444 0.97493036 0.98050139 0.93036212]
0.01 [0.96388889 0.91944444 0.96657382 0.96935933 0.92479109]
0.1 [0.96388889 0.91944444 0.96657382 0.9637883  0.92479109]


In [18]:
my_new_model = SVC(C=0.1, kernel='rbf')

In [19]:
my_new_model.fit(X,y)

SVC(C=0.1)

In [20]:
cross_val_score(my_new_model, X, y, cv=5)

array([0.925     , 0.91111111, 0.94428969, 0.97493036, 0.90250696])

In [23]:
for i in [1E-4,1E-3,1E-2,1E-1]:
    my_new_model.C = i
    print(i, cross_val_score(my_new_model, X, y, cv=5, scoring='accuracy'))

0.0001 [0.1        0.1        0.20334262 0.19777159 0.19220056]
0.001 [0.1        0.1        0.20334262 0.19777159 0.19220056]
0.01 [0.1        0.125      0.21448468 0.2005571  0.21448468]
0.1 [0.925      0.91111111 0.94428969 0.97493036 0.90250696]


In [24]:
for i in [1E-1,1,10,100,1000]:
    my_new_model.C = i
    print(i, cross_val_score(my_new_model, X, y, cv=5, scoring='accuracy'))

0.1 [0.925      0.91111111 0.94428969 0.97493036 0.90250696]
1 [0.96111111 0.94444444 0.98328691 0.98885794 0.93871866]
10 [0.98055556 0.95833333 0.98328691 0.98885794 0.95821727]
100 [0.98055556 0.95833333 0.98328691 0.98885794 0.95821727]
1000 [0.98055556 0.95833333 0.98328691 0.98885794 0.95821727]


In [25]:
X.shape

(1797, 64)